# Generated by Django 5.2.14 on 2026-06-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('periodo_letivo', models.CharField(max_length=20)),
                ('vagas_total', models.PositiveIntegerField()),
                ('vagas_disponiveis', models.PositiveIntegerField()),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
