# Generated by Django 5.2.14 on 2026-06-09 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='periodo_letivo',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='vagas_disponiveis',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='vagas_ocupadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='disciplina',
            table='disciplina',
        ),
        migrations.CreateModel(
            name='HorarioDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sábado')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='disciplinas.disciplina')),
            ],
            options={
                'db_table': 'horario_disciplina',
            },
        ),
    ]
