# Generated by Django 5.2.15 on 2026-06-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='periodo_letivo',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='vagas_disponiveis',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='vagas_total',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.CharField(max_length=20)),
                ('vagas_total', models.PositiveIntegerField()),
                ('vagas_disponiveis', models.PositiveIntegerField()),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['disciplina__nome', 'periodo_letivo'],
                'constraints': [models.UniqueConstraint(fields=('disciplina', 'periodo_letivo'), name='uniq_turma_disciplina_periodo')],
            },
        ),
    ]
