# Generated by Django 5.2.15 on 2026-06-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='alunos.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='disciplinas.disciplina')),
            ],
            options={
                'ordering': ['-criada_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelada'), _negated=True), fields=('aluno', 'disciplina', 'periodo_letivo'), name='uniq_matricula_ativa_por_periodo')],
            },
        ),
    ]
