# Generated by Django 5.2.14 on 2026-06-09 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'periodo_letivo',
            },
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='matricula',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='matriculas.periodoletivo'),
        ),
    ]
