# Generated by Django 5.2.15 on 2026-06-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-criada_em'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
    ]
