# Generated by Django 5.2.15 on 2026-06-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('disciplinas', '0002_remove_disciplina_ativa_and_more'),
        ('matriculas', '0002_alter_matricula_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matricula',
            name='uniq_matricula_ativa_por_periodo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='periodo_letivo',
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='disciplinas.turma'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelada'), _negated=True), fields=('aluno', 'turma'), name='uniq_matricula_ativa_por_turma'),
        ),
    ]
